name: KillMessagePlugin
version: 1.0
main: com.example.killmessageplugin.KillMessagePlugin
api-version: 1.20
description: A plugin to customize kill messages and integrate with SuperVanish.
author: YourName
